### ISSUE TITLE
Check for `include_role` and `import_role` overlaps

### ISSUE THREAD

**Issue by savchenko** [savchenko/ansible-sanity#4]
Ensure that:

1. There is at least one (import|include)_role statement per Playbook task
2. No importing and including is happening in the same task simultaneously
3. No role is imported or included twice

Regarding the №3, consider the following:

```yaml
---
- import_role:
    name: myrole
  vars:
    myvar: False

- include_role:
    name: myrole
  vars:
    myvar: Maybe
```

Suddenly, checking `myvar` is not exactly straightforward.
