### ISSUE TITLE
Detect `when` indented into `set_fact`

### ISSUE THREAD

**Issue by savchenko** [savchenko/ansible-sanity#5]
Both tasks are _technically_ correct, but the second one welcomes unintended behaviour:

```yaml
# Correct statement, tests if `st_client.relay_port` is bool(True)
   - name: Set Relay-server port in Client's config to 22067 as no other port was provided
      set_fact:
         st_client: '{{ st_client | combine( { "relay":{"port":22067} } , recursive=True) }}'
      when: not st_client.relay.port

# Correct statement, sets variable called `when` to `not st_client.relay.port`
   - name: Set Relay-server port in Client's config to 22067 as no other port was provided
      set_fact:
         st_client: '{{ st_client | combine( { "relay":{"port":22067} } , recursive=True) }}'
         when: not st_client.relay.port
```
