### ISSUE TITLE
Count `become` statements per task

### ISSUE THREAD

**Issue by savchenko** [savchenko/ansible-sanity#7]
Valid block, Ansible is happy about it:
```yaml
---
- name: foo
  become: True
  become_user: baz
  ...
  become_user: bar
  ...
  become: False
```
